### PR TITLE
Typography

### PR DESCRIPTION
**Pull request by martypowell**
Addresses #38 

- Updates styles for typography
- Adds section component in order to display typography or a dark section

### CODE REVIEW

**Comment by martypowell** [comment]
@danfox01 @sdurphy I pushed the example up knowing that it probably needs some formatting, but would like you guys to review first. Another issue that needs resolved is the margins/padding for all elements.

**Comment by danfox01** [comment]
@sdurphy the Montserrat body copy seems too heavy. Currently set at 600. Should it be 500?

**Comment by danfox01** [comment]
@martypowell I think we don't want the heading border to span the width of the column. Switching headings to `inline-block` might solve?

**Comment by sdurphy** [comment]
Before approving, can we make the following changes:

- In the Paragraph section we need to change #333 to #292929.
- ~~Can we add 1px of padding to the left and right of the link for Link Focus? (Normal Link, and Normal Link - Sidebar)~~

**Comment by sdurphy** [comment]
Ignore my second bullet about the Link Focus... I was hoping it wouldn't bump anything, but after testing it, it does.

**Comment by martypowell** [comment]
> @martypowell I think we don't want the heading border to span the width of the column. Switching headings to `inline-block` might solve?

@danfox01 we are going to leave this as for this pr. A heading is a block element and I think we will want to keep it that way. The underline is something we will address as part of the inside pages once it comes up.

**Comment by martypowell** [comment]
> Ignore my second bullet about the Link Focus... I was hoping it wouldn't bump anything, but after testing it, it does.

Ignored.

**Comment by martypowell** [comment]
> Before approving, can we make the following changes:
> 
> * In the Paragraph section we need to change #333 to #292929.
> * ~Can we add 1px of padding to the left and right of the link for Link Focus? (Normal Link, and Normal Link - Sidebar)~

@sdurphy wording changed. ready for another look.

**Comment by sdurphy** [comment]
@danfox01 @martypowell, it looks like the font-weight for the right column body copy is too heavy. Can that be brought down to 500 (medium)?

**Comment by martypowell** [comment]
> @danfox01 @martypowell, it looks like the font-weight for the right column body copy is too heavy. Can that be brought down to 500 (medium)?

@sdurphy adjusted

**Comment by danfox01** [comment]
@martypowell Kind of minor for now but we need to update the example text for `Normal Paragraph - Sidebar (Right column on desktop)`. It is just a copy/paste of the other example, but it should be updated to reflect the actual font name (Montserrat) and size (16px). @sdurphy can clarify.

**Comment by martypowell** [comment]
> @martypowell Kind of minor for now but we need to update the example text for `Normal Paragraph - Sidebar (Right column on desktop)`. It is just a copy/paste of the other example, but it should be updated to reflect the actual font name (Montserrat) and size (16px). @sdurphy can clarify.

@danfox01 in the latest update.

**Comment by danfox01** [comment]
Great. On my phone right now and can’t actually hit approve button. Feel free to push through.

Sent with OWA for iPhone

**Review by sdurphy — APPROVED** [review]

**Pull request merged**
