### PR TITLE
Bug 16309 table issues

### PR DESCRIPTION
**Pull request by theilman7**
This fix addresses [bug 16309](https://oittfs.bcg.ad.bcgov.us/BAUCollection/BaltimoreCounty.Gov%20Website/_workitems/edit/16309). Two parts to this pull request.

1. Adds responsive utility for table.
2. Adds `table-layout: fixed;` property to the table when it is nested inside `.dg_card .dg_card__content`. This ensures the table scales properly within the element.

### CODE REVIEW

**Comment by theilman7** [comment]
Bringing branch up-to-date with `integration`.

**Comment by theilman7** [comment]
@martypowell @tmccoy529 @sgrg1 
Just wanted to send a friendly reminder regarding this PR. Should be a small one. Let me know
if you have any questions or suggestions.

**Comment by theilman7** [comment]
@martypowell Ready for another look. I updated the md file as discussed. Let me know if the description makes sense.

**Review by martypowell — APPROVED** [review]

**Comment by martypowell** [comment]
merged on behalf of @theilman7

**Pull request merged**
