### PR TITLE
Fix images css

### PR DESCRIPTION
**Pull request by martypowell**
Site Executive does some weird things with images mainly allows user to set height and width. This attempts to address those issues.

### CODE REVIEW

**Comment by theilman7** [comment]
Branch is out-of-date with integration.

**Comment by martypowell** [comment]
> Branch is out-of-date with integration.

@theilman7 branch is back up to date.

**Review by sgrg1 — APPROVED** [review]
looks good

**Review by theilman7 — APPROVED** [review]
Approved.

**Pull request merged**
