### PR TITLE
Textarea

### PR DESCRIPTION
**Pull request by martypowell**
Addresses #32 

- Added component
- Added styles

### CODE REVIEW

**Comment by danfox01** [comment]
@martypowell looks good except there's a typo in the closing span of the non-React HTML snippet:

`<span class="dg_label-text">Describe your problem/span>`

**Comment by martypowell** [comment]
> @martypowell looks good except there's a typo in the closing span of the non-React HTML snippet:
> 
> `<span class="dg_label-text">Describe your problem/span>`

good catch, will fix.

**Comment by martypowell** [comment]
> > @martypowell looks good except there's a typo in the closing span of the non-React HTML snippet:
> > `<span class="dg_label-text">Describe your problem/span>`
> 
> good catch, will fix.

@danfox01 addressed.

**Comment by danfox01** [comment]
@martypowell we don't want to force all caps for the label or hint. As we discussed this also affects the standard text input, #28.

It also looks like the input label text is too large, but we failed to document that anywhere so I will create a separate issue for that.

**Comment by martypowell** [comment]
> @martypowell we don't want to force all caps for the label or hint. As we discussed this also affects the standard text input, #28.
> 
> It also looks like the input label text is too large, but we failed to document that anywhere so I will create a separate issue for that.

@danfox01 I am resolving now. Confirmed with Sam, label text is 18px.

**Comment by martypowell** [comment]
> > @martypowell we don't want to force all caps for the label or hint. As we discussed this also affects the standard text input, #28.
> > It also looks like the input label text is too large, but we failed to document that anywhere so I will create a separate issue for that.
> 
> @danfox01 I am resolving now. Confirmed with Sam, label text is 18px.

@danfox01 @sdurphy please both review. Bugs that arose should be resolved

- Label and Hint styling
- Bad input focus

**Comment by danfox01** [comment]
@martypowell I'm actually confused about where I can review these changes. The Now link above still shows the previous version.

**Comment by martypowell** [comment]
> @martypowell I'm actually confused about where I can review these changes. The Now link above still shows the previous version.

@danfox01 thats because I never pushed up my changes, it should be deploying now.

**Review by sdurphy — APPROVED** [review]

**Pull request merged**
