### PR TITLE
Alternate Table Layout

### PR DESCRIPTION
**Pull request by martypowell**
Addressed the following table layout

image

- Added examples to the style guide
- Adjusted styles to work on all tables

### CODE REVIEW

**Review by tmccoy529 — DISMISSED** [review]
Looks good to me

**Comment by tmccoy529** [comment]
@martypowell I think this needs a merge with integration

**Comment by sgrg1** [comment]
Looks good to me . Just have a question regarding border-collaspe:collaspe;  th{ backgrond-color:$white  and th{color: $black . Seems to me these property do not seems to be doing anything. Please correct me if I am wrong.

**Comment by martypowell** [comment]
> Looks good to me . Just have a question regarding border-collaspe:collaspe; th{ backgrond-color:$white and th{color: $black . Seems to me these property do not seems to be doing anything. Please correct me if I am wrong.

It is not needed, our reset file handles this.

image

To see more about this check out in general, check out https://developer.mozilla.org/en-US/docs/Web/CSS/border-collapse#result

**Pull request merged**
