### PR TITLE
Add margin card container bug#15173

### PR DESCRIPTION
**Pull request by sgrg1**
small fix, just added top margin.

### CODE REVIEW

**Comment by martypowell** [comment]
@sgrg1 please take a look at the work item 15173 discussion, it has more details on addressing this issue. This only addresses cards, but this needs to account for other components. Please let me know if you have any question.

**Comment by sgrg1** [comment]
@martypowell @tmccoy529 , added _content-top-bottom-margin.scss for top and bottom margin

**Comment by martypowell** [comment]
> @martypowell @tmccoy529 , added _content-top-bottom-margin.scss for top and bottom margin

@sgrg1 this is still just addressing cards, let's talk about this one in person.

**Comment by martypowell** [comment]
@sgrg1 I'm still not sure this will work. An example that breaks this is if we have an app where cards are the first content inside a container. There will be a huge gap between the top of the container and the start of the card list. Let's to put this one on hold until we have more time to figure out.

**Comment by theilman7** [comment]
Would the spacing for this be a one size fits all approach, or would this be more suited to a case-by-case solution and solved with utilities? For example, Bootstrap uses utilities for [margin and padding utilities](https://getbootstrap.com/docs/4.3/utilities/spacing/) for such scenarios. We could of course setup our own version of the utilities to match our naming convention and functionality. Figured I would toss this out there for conversation.

**Comment by martypowell** [comment]
closing, as we have made a decision to handle this at a component level for now.

**Pull request closed without merging**
