### PR TITLE
Bug 16474 - Newsroom - News Cards (on Home Page) IE Issues

### PR DESCRIPTION
**Pull request by theilman7**
This PR addresses bug 16474.

1. Added `max-height: 300px;` and `height: 100%; `to `.dg_date-news-card`. This fixes a bug where IE doesn't calculate height in flex if there isn't a definitive height set.

2. Testing in browser stack revealed there is no longer an issue with the heading text being in all caps. This must have been inadvertently resolved with a previous PR.

### CODE REVIEW

**Comment by martypowell** [comment]
@theilman7 did we confirm this is responsive as well?

**Comment by theilman7** [comment]
@martypowell Checking this now. Noticing the fix in ie is causing issues elsewhere when viewed on mobile in Chrome. Will be taking another look.

**Comment by martypowell** [comment]
> @martypowell Checking this now. Noticing the fix in ie is causing issues elsewhere when viewed on mobile in Chrome. Will be taking another look.

sounds good @theilman7 i know at the time maybe it was okay enough because ie stinks, so it might be worth mentioning this to sam and see what we think.

**Comment by theilman7** [comment]
@martypowell Once the issue with SE is cleared up and we can test the fix in the other repo, we should be able to cancel this PR. You can disregard this item for now.

**Comment by theilman7** [comment]
Cancelling pull request.

**Pull request closed without merging**
