### PR TITLE
Grid

### PR DESCRIPTION
**Pull request by martypowell**
Addresses #49 

- Adds bootstrap grid to the sass project
- Adds documentation to the styleguide for Grid
- Adds other foundational sections (figured i do this while i was in there)

### CODE REVIEW

**Comment by martypowell** [comment]
This is dependent on the #82 pull request.

**Review by danfox01 — COMMENTED** [review]
Looks good. Can we change the description to: 

We use Bootstrap 4's mobile-first flexbox grid system. [See their docs for usage.](https://getbootstrap.com/docs/4.3/layout/grid/)

**Comment by martypowell** [comment]
> Looks good. Can we change the description to:
> 
> We use Bootstrap 4's mobile-first flexbox grid system. [See their docs for usage.](https://getbootstrap.com/docs/4.3/layout/grid/)

will adjust.

**Comment by martypowell** [comment]
> > Looks good. Can we change the description to:
> > We use Bootstrap 4's mobile-first flexbox grid system. [See their docs for usage.](https://getbootstrap.com/docs/4.3/layout/grid/)
> 
> will adjust.

@danfox01 adjusted verbatim.

**Pull request merged**
