### PR TITLE
Bug -1853

### PR DESCRIPTION
**Pull request by theilman7**
This addresses bug [15853](https://oittfs.bcg.ad.bcgov.us/BAUCollection/BaltimoreCounty.Gov%20Website/_workitems/edit/15853). Added styling to prevent the text from expanding out of frame on mobile. Unsure how to provide a sample to render, as the components page doesn't display the search results page.

### CODE REVIEW

**Review by sgrg1 — DISMISSED** [review]
looks good . Travis showed me on his computer

**Review by martypowell — CHANGES_REQUESTED** [review]
@theilman7 can you version bump this badboy please?

**Review by martypowell — APPROVED** [review]

**Comment by martypowell** [comment]
merged on behalf of @theilman7

**Comment by theilman7** [comment]
Version has been bumped.

**Pull request merged**
